<a href="https://colab.research.google.com/github/anushabershilla/Data-science-ML/blob/main/NLP_with_embadingans_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'review':[
        'I love this movie',
        'This movie is amazing',
        'Fantastic acting',
        'I hate this movie',
        'Worst movie ever',
        'This movie is terrible'
    ],
    'sentiment':[1,1,1,0,0,0]
})

df

#Feature set
X = df['review']
y = df['sentiment']

#Tokenizer

from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer()
tokenizer.fit_on_texts(X)
sequences=tokenizer.texts_to_sequences(X)
print(sequences)

#pading
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_paded=pad_sequences(sequences,maxlen=5)
print(X_paded)

#Train test split

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_paded,y,test_size=0.2,random_state=42)

#Build NLP model
import tensorflow as tf
model=tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=50, output_dim=8),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(8, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

#compile model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

#Train model
model.fit(
    X_train,
    y_train,
    epochs=10,
    batch_size=2,
    validation_split=0.2
)

#predict review
new_review = [
    "I love this film"
]

seq = tokenizer.texts_to_sequences(
    new_review
)

pad = pad_sequences(
    seq,
    maxlen=5
)

prediction = model.predict(
    pad
)

print(prediction)

#Evaluate

loss,accuracy = model.evaluate(
    X_test,
    y_test
)

print(accuracy)

prediction = model.predict(pad)

print(prediction)

print((prediction > 0.5).astype(int))

[[3, 5, 2, 1], [2, 1, 4, 6], [7, 8], [3, 9, 2, 1], [10, 1, 11], [2, 1, 4, 12]]
[[ 0  3  5  2  1]
 [ 0  2  1  4  6]
 [ 0  0  0  7  8]
 [ 0  3  9  2  1]
 [ 0  0 10  1 11]
 [ 0  2  1  4 12]]
Epoch 1/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 3s 550ms/step - accuracy: 0.6667 - loss: 0.6956 - val_accuracy: 0.0000e+00 - val_loss: 0.7290
Epoch 2/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step - accuracy: 0.6667 - loss: 0.6902 - val_accuracy: 0.0000e+00 - val_loss: 0.7281
Epoch 3/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 233ms/step - accuracy: 1.0000 - loss: 0.6865 - val_accuracy: 0.0000e+00 - val_loss: 0.7273
Epoch 4/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step - accuracy: 1.0000 - loss: 0.6820 - val_accuracy: 0.0000e+00 - val_loss: 0.7270
Epoch 5/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 217ms/step - accuracy: 1.0000 - loss: 0.6790 - val_accuracy: 0.0000e+00 - val_loss: 0.7265
Epoch 6/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - accuracy: 1.0000 - loss: 0.6760 - val_accuracy: 0.0000e+00 - val_loss: 0.7248
Epoch 7/10
2/2 ━━━━━━━━━━━━━━━━━

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'review':[
        'I love this movie',
        'This movie is amazing',
        'Fantastic acting',
        'I hate this movie',
        'Worst movie ever',
        'This movie is terrible'
    ],
    'sentiment':[1,1,1,0,0,0]
})

df

#Feature set
X = df['review']
y = df['sentiment']

#Tokenizer

from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer()
tokenizer.fit_on_texts(X)
sequences=tokenizer.texts_to_sequences(X)
print(sequences)

#pading
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_paded=pad_sequences(sequences,maxlen=5)
print(X_paded)

#Train test split

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_paded,y,test_size=0.2,random_state=42)

#Build NLP model
import tensorflow as tf
model=tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=50, output_dim=8),
    tf.keras.layers.LSTM(16),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

#compile model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

#Train model
model.fit(
    X_train,
    y_train,
    epochs=10,
    batch_size=2,
    validation_split=0.2
)

#predict review
new_review = [
    "I hate this film"
]

seq = tokenizer.texts_to_sequences(
    new_review
)

pad = pad_sequences(
    seq,
    maxlen=5
)

prediction = model.predict(
    pad
)

print(prediction)

#Evaluate

loss,accuracy = model.evaluate(
    X_test,
    y_test
)

print(accuracy)

prediction = model.predict(pad)

print(prediction)

print((prediction > 0.5).astype(int))

[[3, 5, 2, 1], [2, 1, 4, 6], [7, 8], [3, 9, 2, 1], [10, 1, 11], [2, 1, 4, 12]]
[[ 0  3  5  2  1]
 [ 0  2  1  4  6]
 [ 0  0  0  7  8]
 [ 0  3  9  2  1]
 [ 0  0 10  1 11]
 [ 0  2  1  4 12]]
Epoch 1/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 3s 338ms/step - accuracy: 0.6667 - loss: 0.6940 - val_accuracy: 1.0000 - val_loss: 0.6929
Epoch 2/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6667 - loss: 0.6924 - val_accuracy: 1.0000 - val_loss: 0.6899
Epoch 3/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6667 - loss: 0.6909 - val_accuracy: 1.0000 - val_loss: 0.6868
Epoch 4/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.6667 - loss: 0.6894 - val_accuracy: 1.0000 - val_loss: 0.6836
Epoch 5/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6667 - loss: 0.6879 - val_accuracy: 1.0000 - val_loss: 0.6804
Epoch 6/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6667 - loss: 0.6864 - val_accuracy: 1.0000 - val_loss: 0.6770
Epoch 7/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: